### ISSUE TITLE
configure PYTHONPATH to access mounted repos

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_env_manager#4]
We want mounted repos to access each other before installed repos. 
This code makes the bash export command that needs to be executed in the container

```
import os
# todo: distinguish mounted repos from other mounted directories
def paths_to_mounted_repos(mounted_repo_dirs):
    paths = []
    for mounted_repo_dir in mounted_repo_dirs:
        for entry in os.scandir(mounted_repo_dir):
            # ignore . dirs, and files
            if not entry.name.startswith('.') and entry.is_dir():
                paths.append(os.path.join(mounted_repo_dir, entry.name))
    return paths

def python_path_cmd(dirs, prepend=False):
    """ make bash export command to add dirs to python path"""
    joined_dirs = ':'.join(dirs)
    if prepend:
        bash_cmd = 'export PYTHONPATH={}:$PYTHONPATH'.format(joined_dirs)
    else:
        bash_cmd = 'export PYTHONPATH=$PYTHONPATH:{}'.format(joined_dirs)
    return bash_cmd

MOUNTED_REPO_DIRS = config['container']['paths_to_mount']
python_path_cmd(paths_to_mounted_repos(MOUNTED_REPO_DIRS), prepend=True)
```
But I don't know how to automatically have bash execute this export command when bash starts in the container. Perhaps docker's [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) command would help. Or perhaps the export could be added to one of bash's [initialization files](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_01.html). Our docker container has .bashrc and .profile in root's home dir.

**Comment by jonrkarr** [comment]
I intentionally left this out of `wc_env_manager`, but I'll add this. This
is only necessary for packages that don't have `setup.py` scripts or that
have `setup.py` scripts that you don't want to run for some reason (e.g.
the script is temporarily broken). Otherwise, I recommend using Pip to
manage this for you (as well as install additional dependencies that are
needed). I think this helps avoid ad hoc path manipulation that would need
to be communicated in installation instructions and added to the CircleCI
builds. This is the workflow that I recommend:

   1. Edit `wc_env_manager` config to mount host path(s)
   2. Edit `wc_env_manager` config to use Pip to make editable
   installations of packages within the mounted paths. This will
   1. If needed, uninstall older versions of the packages (delete
      `-egg.link` or package and `-dist-info` in
      `/usr/local/lib/python3.6/site-packages/ `)
      2. Append the paths to the packages to
      `/usr/local/lib/python3.6/site-packages/easy-install.pth`.
      3. Create `/usr/local/lib/python3.6/site-packages/<package>.egg-link`
      which will point to the path to the package.
   3. Use `wc_env_manager` to create a container

Here's an example of the configuration needed for this:

> [wc_env_manager]
>     [[container]]
>         python_packages = '''
>         -e /root/host/Documents/wc_lang
>         -e /root/host/Documents/wc_sim
>         '''
>         [[[paths_to_mount]]]
>             [[[[${HOME}/Documents]]]]
>                 bind = /root/host/Documents/
>                 mode = rw

**Comment by jonrkarr** [comment]
I added the ability to set environment variables (e.g. `PYTHONPATH`) in containers in 0226696a1a0d919b777434132ca92288ed352b00q. The variables will eb set when the container is constructed. This can be controlled via the configuration file. For example:

```
[wc_env_manager]
    [[container]]
        [[[environment]]]
            PYTHONPATH = '/root/host/Documents/wc_lang:/root/host/Documents/wc_utils'
```

FYI, environment variables can be set in several ways. Environment variables will only be persisted when set during image or container creation.

- Set at image creation (`docker build`). In this case, the values persist (until overwritten)
- Set at container creation (`docker run`). In this case, the values persist (until overwritten)
- Set at container execution (`docker exec`). In this case, the values only apply to that particular execution of the container.
- Set within container execution (e.g. `docker run bash -c "VAR=VAL"` or  `docker exec <container> bash -c "VAR=VAL"`). In this case, values will also not be persisted.
